---
title: "03_Main_Analysis"
output: html_document
date: "2026-02-06"
---



```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r}
############################################################
# 0. Load packages and define paths
############################################################

library(tidyverse)
library(lme4)
library(lmerTest)
library(broom.mixed)
library(ggeffects)
library(ggplot2)
library(modelsummary)
library(multcomp)
library(emmeans)
library(performance)
library(DHARMa)
library(simr)
library(forcats)
library(pandoc)

# Define input and output directories
processed_dir <- "data_processed"
output_dir <- "output"

dir.create(output_dir, showWarnings = FALSE)

# Load final analytical dataset
df_fake <- read_csv(file.path(processed_dir, "df_fake.csv"), show_col_types = FALSE)

# Ensure correct variable types
df_fake <- df_fake %>%
  mutate(
    study_id        = factor(study_id),
    item_id         = factor(item_id),
    participant_id  = factor(participant_id),
    experiment_type = factor(experiment_type),
    gender          = factor(gender),
    ideology        = factor(ideology),
    veracity        = factor(veracity),
    share_z         = as.numeric(share_z),
    share_intent    = as.numeric(share_intent),
    age             = as.numeric(age),
    age_z           = as.numeric(age_z)
  )
```

```{r}
############################################################
# 1. Main-effects model
############################################################

m_main <- lmer(
  share_z ~ accuracy_nudge + rating_shown + label_shown +
    (1 | study_id) + (1 | item_id) + (1 | participant_id),
  data = df_fake,
  REML = TRUE
)

summary(m_main)

main_tidy <- broom.mixed::tidy(m_main, effects = "fixed", conf.int = TRUE)

main_effects <- main_tidy %>%
  filter(term %in% c("accuracy_nudge", "rating_shown", "label_shown")) %>%
  mutate(
    term_clean = case_when(
      term == "accuracy_nudge" ~ "Accuracy nudge",
      term == "rating_shown"   ~ "Source rating",
      term == "label_shown"    ~ "Fact-check label",
      TRUE ~ term
    )
  )

main_effects
```
```{r}
############################################################
# 2. Main-effects table
############################################################

modelsummary(
  list("Main effects model" = m_main),
  coef_map = c(
    "accuracy_nudge" = "Accuracy nudge",
    "rating_shown"   = "Source rating",
    "label_shown"    = "Fact-check label"
  ),
  statistic = c("({p.value})", "conf.int"),
  gof_omit = "ICC|Var",
  output = file.path(output_dir, "modelsummary_main_effects.docx")
)

write_csv(main_effects, file.path(output_dir, "main_effects.csv"))

```


```{r}
############################################################
# 3. Forest plot of main effects
############################################################

plot_data <- main_effects %>%
  mutate(
    intervention = factor(
      term_clean,
      levels = c("Accuracy nudge", "Source rating", "Fact-check label")
    )
  )

plot_main <- ggplot(plot_data, aes(x = intervention, y = estimate)) +
  geom_point(size = 3) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.1) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  coord_flip() +
  theme_minimal() +
  labs(
    title = "Standardized effects of anti-misinformation interventions",
    x = "Intervention",
    y = "Effect on standardized sharing intention"
  )

plot_main

ggsave(
  filename = file.path(output_dir, "figure_main_effects.png"),
  plot = plot_main,
  width = 6,
  height = 4,
  dpi = 300
)
```


```{r}
############################################################
# 4. H2 ranking tests
############################################################

h2_tests <- glht(
  m_main,
  linfct = rbind(
    "Label vs Nudge"  = c(0, -1, 0, 1),
    "Nudge vs Source" = c(0, 1, -1, 0),
    "Label vs Source" = c(0, 0, -1, 1)
  )
)

summary(h2_tests)
```

```{r}
############################################################
# 5. Predicted values by intervention
############################################################

eff_acc <- ggpredict(m_main, terms = "accuracy_nudge")
eff_rat <- ggpredict(m_main, terms = "rating_shown")
eff_lab <- ggpredict(m_main, terms = "label_shown")

eff_acc$intervention <- "Accuracy nudge"
eff_rat$intervention <- "Source rating"
eff_lab$intervention <- "Fact-check label"

eff_all <- bind_rows(eff_acc, eff_rat, eff_lab)

plot_predicted <- ggplot(
  eff_all,
  aes(x = x, y = predicted, color = intervention)
) +
  geom_point(size = 3) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.1) +
  facet_wrap(~ intervention) +
  theme_minimal() +
  labs(
    x = "Condition (0 = Control, 1 = Treatment)",
    y = "Predicted standardized sharing intention",
    title = "Predicted sharing intentions under control and intervention conditions"
  )

plot_predicted
```



```{r}
############################################################
# 6. Robustness: separate intervention models
############################################################

m_nudge <- lmer(
  share_z ~ accuracy_nudge +
    (1 | study_id) + (1 | item_id) + (1 | participant_id),
  data = df_fake,
  REML = TRUE
)

m_rating <- lmer(
  share_z ~ rating_shown +
    (1 | study_id) + (1 | item_id) + (1 | participant_id),
  data = df_fake,
  REML = TRUE
)

m_label <- lmer(
  share_z ~ label_shown +
    (1 | study_id) + (1 | item_id) + (1 | participant_id),
  data = df_fake,
  REML = TRUE
)

summary(m_nudge)
summary(m_rating)
summary(m_label)
```

```{r}
############################################################
# 7. Ideology heterogeneity
############################################################

df_fake_ideo <- df_fake %>%
  filter(ideology %in% c("Democrat", "Republican")) %>%
  mutate(ideology = droplevels(ideology),
         ideology = relevel(ideology, ref = "Democrat"))

table(df_fake_ideo$ideology)

m_ideo <- lmer(
  share_z ~ (accuracy_nudge + rating_shown + label_shown) * ideology +
    (1 | study_id) + (1 | item_id) + (1 | participant_id),
  data = df_fake_ideo,
  REML = TRUE
)

summary(m_ideo)

ideo_tidy <- broom.mixed::tidy(m_ideo, effects = "fixed", conf.int = TRUE)
ideo_tidy
```

```{r}
############################################################
# 8. Ideology subgroup forest plot
############################################################

acc_eff <- emmeans(m_ideo, ~ accuracy_nudge | ideology) %>%
  contrast(method = "revpairwise") %>%
  confint() %>%
  as.data.frame() %>%
  mutate(intervention = "Accuracy nudge")

rat_eff <- emmeans(m_ideo, ~ rating_shown | ideology) %>%
  contrast(method = "revpairwise") %>%
  confint() %>%
  as.data.frame() %>%
  mutate(intervention = "Source rating")

lab_eff <- emmeans(m_ideo, ~ label_shown | ideology) %>%
  contrast(method = "revpairwise") %>%
  confint() %>%
  as.data.frame() %>%
  mutate(intervention = "Fact-check label")

plot_ideo <- bind_rows(acc_eff, rat_eff, lab_eff) %>%
  rename(
    group = ideology,
    effect = estimate,
    effect_low = asymp.LCL,
    effect_high = asymp.UCL
  )

plot_ideo_fig <- ggplot(
  plot_ideo,
  aes(x = intervention, y = effect, colour = group)
) +
  geom_point(position = position_dodge(width = 0.5), size = 3) +
  geom_errorbar(
    aes(ymin = effect_low, ymax = effect_high),
    position = position_dodge(width = 0.5),
    width = 0.1
  ) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  coord_flip() +
  theme_minimal() +
  labs(
    title = "Intervention effects by political ideology",
    x = "Intervention",
    y = "Treatment effect on standardized sharing intention",
    colour = "Ideology"
  )

plot_ideo_fig

ggsave(
  filename = file.path(output_dir, "figure_ideology_effects.png"),
  plot = plot_ideo_fig,
  width = 7,
  height = 4,
  dpi = 300
)
```



```{r}
############################################################
# 9. Age heterogeneity
############################################################

m_age <- lmer(
  share_z ~ (accuracy_nudge + rating_shown + label_shown) * age_z +
    (1 | study_id) + (1 | item_id) + (1 | participant_id),
  data = df_fake,
  REML = TRUE
)

summary(m_age)

age_tidy <- broom.mixed::tidy(m_age, effects = "fixed", conf.int = TRUE)
age_tidy
```


```{r}
############################################################
# 10. Age heterogeneity plot
############################################################

age_grid <- seq(
  from = min(df_fake$age_z, na.rm = TRUE),
  to   = max(df_fake$age_z, na.rm = TRUE),
  length.out = 50
)

acc_emm <- emmeans(
  m_age,
  ~ accuracy_nudge | age_z,
  at = list(age_z = age_grid, rating_shown = 0, label_shown = 0)
)

acc_eff <- contrast(acc_emm, method = "revpairwise") %>%
  confint() %>%
  as.data.frame() %>%
  mutate(intervention = "Accuracy nudge")

rat_emm <- emmeans(
  m_age,
  ~ rating_shown | age_z,
  at = list(age_z = age_grid, accuracy_nudge = 0, label_shown = 0)
)

rat_eff <- contrast(rat_emm, method = "revpairwise") %>%
  confint() %>%
  as.data.frame() %>%
  mutate(intervention = "Source rating")

lab_emm <- emmeans(
  m_age,
  ~ label_shown | age_z,
  at = list(age_z = age_grid, accuracy_nudge = 0, rating_shown = 0)
)

lab_eff <- contrast(lab_emm, method = "revpairwise") %>%
  confint() %>%
  as.data.frame() %>%
  mutate(intervention = "Fact-check label")

plot_age_clean <- bind_rows(acc_eff, rat_eff, lab_eff) %>%
  rename(
    effect = estimate,
    effect_low = asymp.LCL,
    effect_high = asymp.UCL
  )

plot_age_fig <- ggplot(
  plot_age_clean,
  aes(x = age_z, y = effect)
) +
  geom_ribbon(aes(ymin = effect_low, ymax = effect_high), alpha = 0.15) +
  geom_line(linewidth = 1.2) +
  facet_wrap(~ intervention) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  theme_minimal(base_size = 12) +
  labs(
    title = "Estimated intervention effects across age",
    x = "Standardized age",
    y = "Treatment effect on standardized sharing intention"
  )

plot_age_fig

ggsave(
  filename = file.path(output_dir, "figure_age_effects.png"),
  plot = plot_age_fig,
  width = 7,
  height = 4,
  dpi = 300
)
```


```{r}
table(df_fake$accuracy_nudge, cut(df_fake$age_z, breaks = c(-Inf,-1,0,1,Inf)))
```




```{r}
############################################################
# 11. Gender heterogeneity
############################################################

df_fake <- df_fake %>%
  mutate(gender = fct_relevel(gender, "Female"))

m_gender <- lmer(
  share_z ~ (accuracy_nudge + rating_shown + label_shown) * gender +
    (1 | study_id) + (1 | item_id) + (1 | participant_id),
  data = df_fake,
  REML = TRUE
)

summary(m_gender)

gender_tidy <- broom.mixed::tidy(m_gender, effects = "fixed", conf.int = TRUE)
gender_tidy

```


```{r}
############################################################
# 12. Gender subgroup forest plot
############################################################

acc_eff <- emmeans(m_gender, ~ accuracy_nudge | gender) %>%
  contrast(method = "revpairwise") %>%
  confint() %>%
  as.data.frame() %>%
  mutate(intervention = "Accuracy nudge")

rat_eff <- emmeans(m_gender, ~ rating_shown | gender) %>%
  contrast(method = "revpairwise") %>%
  confint() %>%
  as.data.frame() %>%
  mutate(intervention = "Source rating")

lab_eff <- emmeans(m_gender, ~ label_shown | gender) %>%
  contrast(method = "revpairwise") %>%
  confint() %>%
  as.data.frame() %>%
  mutate(intervention = "Fact-check label")

plot_gender <- bind_rows(acc_eff, rat_eff, lab_eff) %>%
  rename(
    group = gender,
    effect = estimate,
    effect_low = asymp.LCL,
    effect_high = asymp.UCL
  )

plot_gender$intervention <- factor(
  plot_gender$intervention,
  levels = c("Accuracy nudge", "Source rating", "Fact-check label")
)

plot_gender_fig <- ggplot(
  plot_gender,
  aes(x = intervention, y = effect, colour = group)
) +
  geom_point(position = position_dodge(width = 0.5), size = 3) +
  geom_errorbar(
    aes(ymin = effect_low, ymax = effect_high),
    position = position_dodge(width = 0.5),
    width = 0.1
  ) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  coord_flip() +
  theme_minimal(base_size = 12) +
  labs(
    title = "Intervention effects by gender",
    x = "Intervention",
    y = "Treatment effect on standardized sharing intention",
    colour = "Gender"
  )

plot_gender_fig

ggsave(
  filename = file.path(output_dir, "figure_gender_effects.png"),
  plot = plot_gender_fig,
  width = 7,
  height = 4,
  dpi = 300
)
```

```{r}
############################################################
# 13. Combined summary forest plot
############################################################

overall <- data.frame(
  intervention = c("Accuracy nudge", "Source rating", "Fact-check label"),
  group = "Overall",
  effect = c(-0.108, -0.045, -0.206),
  effect_low = c(-0.108 - 1.96 * 0.025,
                 -0.045 - 1.96 * 0.013,
                 -0.206 - 1.96 * 0.009),
  effect_high = c(-0.108 + 1.96 * 0.025,
                  -0.045 + 1.96 * 0.013,
                  -0.206 + 1.96 * 0.009)
)

# Ideology effects (aus emmeans)
ideo_plot <- plot_ideo %>%
  mutate(group = ifelse(group=="Democrat","Democrat","Republican")) %>%
  dplyr::select(intervention,group,effect,effect_low,effect_high)

# Gender effects
gender_plot <- plot_gender %>%
  dplyr::select(intervention,group,effect,effect_low,effect_high)

# alles zusammen
combined_effects <- bind_rows(
  overall,
  ideo_plot,
  gender_plot
)

combined_effects$intervention <- factor(
  combined_effects$intervention,
  levels = c("Accuracy nudge","Source rating","Fact-check label")
)

############################################################
# Plot
############################################################

ggplot(combined_effects,
       aes(x = effect,
           y = intervention,
           colour = group)) +

  geom_point(position = position_dodge(width = 0.6), size = 3) +

  geom_errorbar(
    aes(xmin = effect_low, xmax = effect_high),
    position = position_dodge(width = 0.6),
    height = 0.2
  ) +

  geom_vline(xintercept = 0, linetype = "dashed") +

  theme_minimal(base_size = 12) +

  labs(
    title = "Intervention effects across demographic groups",
    x = "Effect on standardized sharing intention",
    y = "Intervention",
    colour = "Group"
  )

ggsave(
  file.path(output_dir,"figure_summary_effects.png"),
  width = 8,
  height = 5,
  dpi = 300
)
```

```{r}
############################################################
# 14. Leave-one-study-out sensitivity analysis
############################################################

experiments <- unique(df_fake$experiment_type)

m_full <- lmer(
  share_z ~ accuracy_nudge + rating_shown + label_shown +
    (1 | study_id) + (1 | item_id) + (1 | participant_id),
  data = df_fake,
  REML = TRUE
)

full_coefs <- summary(m_full)$coefficients
print(round(full_coefs, 4))

loso_results <- list()

for (exp in experiments) {
  df_sub <- df_fake[df_fake$experiment_type != exp, ]

  remaining_studies <- length(unique(df_sub$study_id))

  if (remaining_studies > 1) {
    mod <- lmer(
      share_z ~ accuracy_nudge + rating_shown + label_shown +
        (1 | study_id) + (1 | item_id) + (1 | participant_id),
      data = df_sub, REML = TRUE
    )
  } else {
    mod <- lmer(
      share_z ~ accuracy_nudge + rating_shown + label_shown +
        (1 | item_id) + (1 | participant_id),
      data = df_sub, REML = TRUE
    )
  }

  coefs <- summary(mod)$coefficients

  for (term in rownames(coefs)) {
    loso_results[[length(loso_results) + 1]] <- data.frame(
      excluded = exp,
      term = term,
      estimate = coefs[term, "Estimate"],
      se = coefs[term, "Std. Error"],
      p = coefs[term, "Pr(>|t|)"]
    )
  }
}

loso_df <- do.call(rbind, loso_results)
rownames(loso_df) <- NULL

loso_df

write_csv(loso_df, file.path(output_dir, "loso_results.csv"))
```


```{r}
############################################################
# 15. Robustness checks
############################################################

# 16.1 Alternative outcome
m_raw <- lmer(
  share_intent ~ accuracy_nudge + rating_shown + label_shown +
    (1 | study_id) + (1 | item_id) + (1 | participant_id),
  data = df_fake,
  REML = TRUE
)

summary(m_raw)

# 16.2 Additional covariates
m_cov <- lmer(
  share_z ~ accuracy_nudge + rating_shown + label_shown +
    age_z + ideology + gender +
    (1 | study_id) + (1 | item_id) + (1 | participant_id),
  data = df_fake,
  REML = TRUE
)

summary(m_cov)

```


```{r}
############################################################
# 16. ICC and variance decomposition
############################################################

m0 <- lmer(
  share_z ~ 1 + (1 | study_id) + (1 | participant_id) + (1 | item_id),
  data = df_fake
)

icc(m0)

VarCorr(m0)

vc <- as.data.frame(VarCorr(m0))
vc$share <- vc$vcov / sum(vc$vcov)
vc[, c("grp", "vcov", "share")]

```


```{r}
############################################################
# 17. Marginal and conditional R2
############################################################

r2_nakagawa(m_main)

```

```{r}
############################################################
# 18. Residual diagnostics
############################################################

sim_res <- simulateResiduals(fittedModel = m_main, n = 500)

png(file.path(output_dir, "residual_diagnostics.png"),
    width = 10, height = 5, units = "in", res = 300)
plot(sim_res)
dev.off()
```


```{r}
############################################################
# 19. ML model comparison
############################################################

m0_ml <- lmer(
  share_z ~ 1 + (1 | study_id) + (1 | participant_id) + (1 | item_id),
  data = df_fake,
  REML = FALSE
)

m1_ml <- lmer(
  share_z ~ accuracy_nudge + rating_shown + label_shown +
    (1 | study_id) + (1 | participant_id) + (1 | item_id),
  data = df_fake,
  REML = FALSE
)

anova(m0_ml, m1_ml)
AIC(m0_ml, m1_ml)
BIC(m0_ml, m1_ml)

```



